# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_invitation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='caregiving',
            name='elder_id',
        ),
        migrations.RemoveField(
            model_name='caregiving',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='daily_condition',
            name='elder_id',
        ),
        migrations.RemoveField(
            model_name='disease_hist',
            name='elder_id',
        ),
        migrations.RemoveField(
            model_name='emergency_call',
            name='elder_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='log_tracker',
            name='elder_id',
        ),
        migrations.RemoveField(
            model_name='log_tracker',
            name='tracker_id',
        ),
        migrations.RemoveField(
            model_name='medical_treatment_hist',
            name='elder_id',
        ),
        migrations.RemoveField(
            model_name='medications',
            name='elder_id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='elder_id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Notif_template',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='elder_id',
        ),
        migrations.DeleteModel(
            name='Point_of_interest',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='respond_emergency_call',
            name='emergency_call_id',
        ),
        migrations.RemoveField(
            model_name='respond_emergency_call',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Tracker_template',
        ),
        migrations.DeleteModel(
            name='Admin_invitation',
        ),
        migrations.DeleteModel(
            name='Caregiving',
        ),
        migrations.DeleteModel(
            name='Daily_condition',
        ),
        migrations.DeleteModel(
            name='Disease_hist',
        ),
        migrations.DeleteModel(
            name='Elder',
        ),
        migrations.DeleteModel(
            name='Emergency_call',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Log_tracker',
        ),
        migrations.DeleteModel(
            name='Medical_treatment_hist',
        ),
        migrations.DeleteModel(
            name='Medications',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='Posting',
        ),
        migrations.DeleteModel(
            name='Respond_emergency_call',
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
